services:
    davidiq.AdvancedPolls.listener:
        class: davidiq\AdvancedPolls\event\main_listener
        arguments:
            - @dbal.conn
            - @template
        tags:
            - { name: event.listener }
