services:
    davidiq.MultiGroupedPolls.listener:
        class: davidiq\MultiGroupedPolls\event\main_listener
        arguments:
            - @dbal.conn
            - @template
        tags:
            - { name: event.listener }
